### ISSUE TITLE
Intermittent failures in e2e tests in GitHub CI

### ISSUE THREAD

**Issue by praveingk** [clusterlink-net/clusterlink#94]
Experience random failures due to several reasons, related to the environment in e2e tests in GitHub CI environment.

**Comment by praveingk** [comment]
@kfirtoledo @orozery  Do we need k8s.sh? since the go e2e tests support new controlplane.

**Comment by orozery** [comment]
> @kfirtoledo @orozery Do we need k8s.sh? since the go e2e tests support new controlplane.

I think we can remove it from the CI, but I would keep it for dev use.

**Comment by orozery** [comment]
Actually, we cannot yet remove it from the CI as well as the go-dataplane is not tested elsewhere.

**Comment by kfirtoledo** [comment]
Two options:
1) Fix the bug in the k8s.sh
2) Add the go dataplane to the go tests and remove the k8s.sh from the CI for now

**Comment by orozery** [comment]
Anyhow I'm working on a new go-test framework which will hopefully will be ready next week.
I think in the meantime we can simply re-run failed jobs.
Of course anyone is welcome to execute one of the 2 options @kfirtoledo suggested.

**Comment by kfirtoledo** [comment]
Anyway, this is a temporary solution, I will raise a PR for the second solution when the CI passes without any issues (this is not a lot of work).

**Comment by orozery** [comment]
I merged #98 and #101 which should resolve this issue (CI e2e tests failing).
For now, keeping this open for 2 reasons:
1. To verify that these PRs indeed fixed the issue, and the CI is now stable.
2. Use this issue to track the go-dataplane bug (which is now referred to in here: https://github.com/clusterlink-net/clusterlink/blob/7b05ebd41ab658e04925f8f27f0d931c2bf935ef/.github/workflows/pr-e2e-test.yml#L31)

**Comment by elevran** [comment]
Following the switch to the new e2e framework, still seeing some intermittent failures relating to KIND clusters not ready within the timeout (a few minutes). Subsequent runs seem to pass...

**Comment by orozery** [comment]
Previous errors were fixed. Closing until a new evidence shows.
